{% set version = '1.20.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-getopt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/getopt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/getopt/getopt_{{ version }}.tar.gz
  sha256: 531f5fdfdcd6b96a73df2b39928418de342160ac1b0043861e9ea844f9fbf57f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, testthat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('getopt')"           # [not win]
    - "\"%R%\" -e \"library('getopt')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/trevorld/r-getopt
  license: GPL (>= 2)
  summary: Package designed to be used with Rscript to write ``#!'' shebang scripts that accept
    short and long flags/options. Many users will prefer using instead the packages
    optparse or argparse which add extra features like automatically generated help
    option and usage, support for default values, positional argument support, etc.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: getopt
# Type: Package
# Title: C-Like 'getopt' Behavior
# Version: 1.20.3
# Authors@R: c(person("Trevor L", "Davis", role=c("aut", "cre"), email="trevor.l.davis@gmail.com"), person("Allen", "Day", role="aut", comment="Original package author"), person("Roman", "Zenka", role="ctb"))
# URL: https://github.com/trevorld/r-getopt
# Imports: stats
# BugReports: https://github.com/trevorld/r-getopt/issues
# Description: Package designed to be used with Rscript to write ``#!'' shebang scripts that accept short and long flags/options. Many users will prefer using instead the packages optparse or argparse which add extra features like automatically generated help option and usage, support for default values, positional argument support, etc.
# License: GPL (>= 2)
# Suggests: covr, testthat
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-22 19:27:49 UTC; trevorld
# Author: Trevor L Davis [aut, cre], Allen Day [aut] (Original package author), Roman Zenka [ctb]
# Maintainer: Trevor L Davis <trevor.l.davis@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-03-22 20:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
