travis:
  secure:
    BINSTAR_TOKEN: OWLfIbDRGu0VQ5JPNemahRlqlfu5XORKTgMpa0ze5ALTkqOA4/adNpYar8k9iecltpewvKL2qBGXKIZrzOhLqS6xj3Tg1NCiIexkYKiU4ZS9YyZJx55vuOZaJxXGYwyc/PiVnKTUIuy7QeR3SSqNc7kjReLJ3OvUNjg6aTTJZHNbpIobnaHLYIDISNIDXW+xLo9BXx5ERqUiqcETs9vXKQnrentmNDCi8fAWRPW3QUEfolxz8WObtVCssHyn+QTpMBf67iIro7mayX2OcyhBmhytnJI8DlUODoyLGjMvWGSTzPb98OdnMmv+/3wSDjgqdrh/T0lPEvafNcR9mfJ+Z/biYhyt1pZtPDdIZ5FCO8ShgJtm2b+NWT39a9XoH1PKHD8aenmuvMNu+F4tUVYEe37caJIxrBxIVgeGBOYhSThoCx5BL6H3Xg6uNTWez/+FkUNhDcbkudAf6JrWe0DApb+JkhN0PfXBLGkMzcfz6loc2DXhhi77hNQmwPSiPKRnMNF+0G7dao5wXDu5Y14f+GgX+4I+qoqghrUohk9gNR3thPkQVHJA1hNioZjnPh0GQAiWHyLdJh4AAZcevDvQLwK1Fay5e2dmumAukftI3UtLFAyIWUr8p0FOJNBeMiUBcJtkmUDvdcNbhNzrHbuhtx8+i9uSvhD69WHqtOBwh+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
