travis:
  secure:
    BINSTAR_TOKEN: V5dlIuQllWNtESzdgraTD3udyWFT/8o/Oc0sKlvCdZmX6k+GHpPYHpTOAbiL+zLvkRF15nv+Y5qAWeqEGw6w7ScB/dU7Qmf1hbkgV/411Bgw6bLublhvskIKbd+pYyoxcKSknfw1GzF5L5GM0D+fB79eXzBQJSE6AfjI39hFORlKFQdjLH74Fj5ypLA8h65e1wXFkajCQgsbZG/a7QPwZfHWj1TWQdPLMDWczqtCBTnMzZ81ei+UVOOpn5ldbqJ0ZdIQAoM3T74ym9J+GuoEO+kYm2/Q1JKn9bAZ0ZzKpleYcO4AvkpnUki5xAcE37qGiXbOAVKa2XowKZZiSEjQ1TtpgaBHQ2iqxroDMrA7FG9dsCzN5fx58HJNr5+t+Y/JF8bWVUbjkEeuyCvzI/I9dZDbygg11iSJy3ZAV3v3Gjm80PNQXzmKyqQIevnyzKJZXap7waM1/Tr8RNnMhMy3y0M20SjFk2nlrxVzMTELMr4Xj4qpgtsOqJSDGBkbrKwiSpj/nEE7RgI/bu3i3BFwGRdHMgRSlo378t2CKmcqQDwvtrQss0wFgUbqCB0Xx8Ascf5MwPeIOpdEZZGWarnaw5mxYmQAbb7hm9B/n37oiNvYTDW9iJimEQF8QrVDYuITAYs5pxSgRxORa7z3wXxGQnmvJPrsA3iTkYHojccSuzo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
