travis:
  secure:
    BINSTAR_TOKEN: JVQJLXvxu/d2RQppWCR2qIEK+5KmffHaZ6LO0TLrbk03jRDAbvDh/RmUPEVMoviRmXFncAORihxqG98al42Sh12gzHywwV9PG6Nb1I2dBwgAo36rU/57QV7KlcZm7HgP/ufROOcd3hbNglRZuzGPtgUs+EBIZTTNCqlrGpgI4kpiBuxjeAk0x/3f5hO8BUFNnBw0GKWQbwTjdo1iU8qJpJJMST0+SB8NivxVenl+cCGj/JJ82vgAZj1pvz/iY8QtCT3H+EQyAHaKMLWMc5R7aj7Zyv5RGxSKXg85zocoKixpgxhW4kIy3gSUf2Cc4c8MTbkpVphtOmICYo8t66CbDJsY1RrfP6fF1PEti65PiokroQBmp3639rk/pXI5Ll8Zybhxs/EbX8i91BMgNSHvxKlVWkrsGJTZJFwOmfDR10n/+thxXNVmrn1XOcgDoM5wzh84RySMfGCHDmbky7l+5LmP6D9A6RIlr5x9G615YLAyNudh6UciP73FbfR+dGzFsukRvsW9Iyb/8rrDUPqGvJPaouYnJPXrmhaghGohRQI4mK4gYcu4KEELZT040S6ZEzYOqLhVY/nNYyQGKl7KlhvSFJ9VAK3InTlp8MbvIlkQnaJwemlzT6yzppOiioqYgK6THA0mkmy3gNxXJasBCtEZnDDFc5LWHTC/iohU6rY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
