travis:
  secure:
    BINSTAR_TOKEN: jCy20B3INwzs7XrjJFQhdXzjGJvoju7MdIFQfBwkMdD//+1mlNmdtvyoYFHGB71WpUi8v7t2q+UzJwlePI3vET+Fg9NUp/by7gLOY6B9XhauhqPjhRDGSt3cI+LV1kO+thBI6iq/QhUzmBiO2yor+3eUb0eOznwkiEanh9K/CT9bKtigkbW5bubazJGd3hXryfRHY+2YYaFgu3xc5p1lnsNkm7WdtRIdZpWNNj7hq32TJGb5YebFZCkKN28YLShwTiniS1IGHbpkNh0Sx9rhLAd0yyO6bN4JjP9jY29q8KT9ZjBmGU4uSdKVCxZ5rQC4o3aVMKTk4BeR8qEffgLf4rUTtK1vuN0DcXsXeslnnTzVLn07/HQ4DZkDg4+NaXFMwice41SMWwjDSl1ejt2If/pYHhgpTKcp2Ax7taDfPEihTBlxB1RMO2t5efZryY1/OUU3Zh1HNRnhS3d7mhtMkahwd1uesN7Zy3e7/jXdCB7nUT+9oY5CUOBujsJ081e0LcJtky+g2/MLjuGmQV75nzXL75DnbVDpc57Ehhjybb7TxQc3B34Xpn7U3TH3CnvrmYdrjEvtYJCUO955RKpGOIsKaLDhae0YcN+Sv8oQNwnQoegNYOa3k+Q8mWT+cihQKwcEJvH89wAe7zDOyDmpqJ4k8gb5/wExRCdkh60C4jA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
