travis:
  secure:
    BINSTAR_TOKEN: UZuyZu4Cuw3ThYkCm1YK0Kbf5XdGiIcvXySds2gfHPPl5Azh8uILYR/VASwaKhLa7zu45QA+lOGjBgV8eL47SKggfm0UVxNYmqsRw1iSd/Wd4EvL33Jlh2DWCXSKQtoZVmMsnngdpVI5o5tYy+vmld5t2Yh6Hj0QxQShVOto1/hp193Jeugo6b8AGh+5bo19bNXXNc3nKKD/2K62IgC8A3p+2eUFjeuOoLD5RSfiiuYFlv9PYD0dTSYaWmJKKHvtY0Son2d8Tc0T3HqyrMZBsBrsOQps6XwddgkOz8CsW3eOtoHSYiSDbdG/R9iAyXQb//jpJgP7aAiJcNY4eYGXZc43Qrhf2guT6lemwq+X/XBwCnSVXfF88GywTdaZNEOAp/E4icnnNTqUEbQizM6XXjli1qiO1X5oT/tCVz6WZFZSjOCz3iJs+5FMqSWWEGwo1U5O4f3ki7gA7Pb++xAkz3U/w7n4ALtKhaCywDO/Q9cMkpCTyYibewF26JmBZJ1jmXiNjSqmO6i9Wh8Meg/WN81Bdb4aAUUCcKG1FpF7zyDM7yOwgaRd7VKtIaHNCUOdofzlUvzQWRqmpbYH4DthL+hYkzU7IbkqFAAEvHodiFpHtwrSlY/Ddn5cvDMNyBvph+29+XyM2TusfvYv9xhuh4zQ8vAfxFUzT5hb6BqXziQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
